const express = require('express')
const path = require("path")
const app = express()
const s_html = path.join(__dirname,"../html")
const s_css = path.join(__dirname,"../css")
const s_image = path.join(__dirname,"../image")
app.use(express.static(s_html))
app.use(express.static(s_css))
app.use(express.static(s_image))
app.listen(3040)